export const planningEnglish: Record<string, string> = {
  "교체·이동 시간은 0~240분으로 입력해주세요.": "Enter 0–240 minutes for changeover and travel.",
  "취소 사유와 게스트 링크 처리 방법을 선택해주세요.": "Enter a cancellation reason and choose how to handle the guest link.",
  "다른 확정 부킹이 사용하는 링크입니다. 유지한 뒤 링크 관리에서 조정해주세요.": "Another confirmed booking uses this link. Keep it and review it in Links.",
  "소개·기술자료를 등록한 뒤 검토 완료로 기록해주세요.": "Add press materials and a technical rider before recording the review.",
  "행사 자료 운영팀 검토 완료": "Event materials reviewed by operations",
  "부킹 담당자 지정": "Assign a booking owner",
  "오늘까지 후속 업무 처리": "Follow-up due today",
  "기한 지난 후속 업무 처리": "Overdue follow-up",
  "일정 필터": "Schedule filters",
  "필터": "Filters",
  "후속 업무 기한 지정": "Set a follow-up due date",
  "지난 홀드 재협의": "Revisit expired hold",
  "교체·이동 포함 일정 겹침": "Schedule conflict including changeover or travel",
  "상대가 일정 조정 요청": "Artist requested a schedule adjustment",
  "변경 일정 가능 여부 재확인": "Recheck availability for the changed schedule",
  "누락된 행사 자료 등록": "Add missing event materials",
  "행사 자료 운영팀 검토": "Review event materials",
  "삭제된 게스트 링크 확인": "Review deleted guest link",
  "게스트 등록 링크 상태 확인": "Review guest registration link status",
  "출연 결과 기록": "Record performance outcome",
  "종료된 행사 부킹 확인": "Review booking for a closed event",
  "남은 준비 업무 처리": "Complete open preparation tasks",
  "일정 변경을 저장한 뒤 상대 가능 여부를 다시 확인해주세요.": "Save the schedule change, then recheck the artist’s availability.",
  "교체·이동 여유 시간": "Changeover and travel buffers",
  "출연 후 무대 교체 (분)": "Stage changeover after performance (minutes)",
  "다음 행사까지 이동 (분)": "Travel to next event (minutes)",
  "취소 기록": "Record cancellation",
  "부킹 취소를 기록했습니다.": "Booking cancellation recorded.",
  "취소 사유": "Cancellation reason",
  "등록 {registered}명 · 입장 {checked}명": "{registered} registered · {checked} checked in",
  "게스트 링크 처리": "Guest link handling",
  "처리 방법 선택": "Choose an action",
  "추가 등록 중지": "Pause new registrations",
  "현재 링크 상태 유지": "Keep current link state",
  "다른 확정 부킹이 같은 링크를 사용 중입니다.": "Another confirmed booking uses the same link.",
  "기존 게스트와 입장 기록은 유지됩니다. 취소 안내는 자동 발송되지 않습니다.": "Existing guests and check-in records are kept. Cancellation notices are not sent automatically.",
  "이 부킹의 확인 필요 항목": "Items to review for this booking",
  "자료 내용과 현장 준비 가능 여부를 확인한 뒤 완료로 기록하세요.": "Review the materials and confirm the venue can meet the requirements before marking reviewed.",
  "행사 자료 검토를 기록했습니다.": "Event materials review recorded.",
  "운영팀 검토 완료": "Mark reviewed by operations",
  "출연 후 교체 {changeover}분 · 다음 행사 이동 {travel}분": "Changeover: {changeover} min · Travel to next event: {travel} min",
  "취소 시 추가 등록 중지": "New registrations paused at cancellation",
  "취소 시 링크 상태 유지": "Link state kept at cancellation",
  "운영팀 자료 검토 완료": "Materials reviewed by operations",
  "운영팀 자료 검토 대기": "Awaiting operations materials review",
  "자료 검토": "Review materials",
  "확인 {count}건": "{count} items to review",

  "문의·조율·홀드": "Enquiries, negotiations and holds",
  "업무 수정": "Edit task",
  "업무 수정 · {title}": "Edit task · {title}",
  "준비 업무 수정": "Edit preparation task",
  "준비 업무를 저장했습니다.": "Preparation task saved.",
  "아티스트 관리": "Artists",
  아티스트: "Artist",
  "부킹 관리": "Bookings",
  부킹: "Booking",
  "공유 일정": "Shared calendar",
  일정: "Calendar",
  "행사 준비": "Event preparation",
  "준비 업무": "Preparation",
  "공연 준비": "Production",
  운영팀: "Operations team",
  "전체 행사 · 공연 준비": "All events · Production",
  "팀 작업 공간": "Team workspace",
  "연락처·자료·출연 이력": "Contacts, materials and performance history",
  "문의·조율·홀드·출연 확정":
    "Enquiries, negotiations, holds and confirmations",
  "출연 시간과 일정 겹침 확인": "Performance times and schedule conflicts",
  "출연표·자료·준비 체크리스트": "Running order, materials and preparation",
  "기존 운영 기능과 새 공연 준비 기능을 확인할 수 있습니다. 샘플 데이터만 변경됩니다.":
    "Explore existing operations and new production workflows. Changes affect sample data only.",
  "아티스트 섭외와 일정·준비 업무를 이어서 관리합니다.":
    "Connect artist bookings, schedules and preparation.",
  "아티스트 추가": "Add artist",
  "아티스트 검색": "Search artists",
  "이름·담당자·에이전시": "Name, contact or agency",
  "공연 형태": "Performance type",
  "아티스트 {count}명": "{count} artists",
  라이브: "Live act",
  밴드: "Band",
  공연자: "Performer",
  "거점 미등록": "City not set",
  "직접 연락": "Direct contact",
  "담당자 미등록": "Contact not set",
  "진행 중 {count}건": "{count} active bookings",
  "기술자료 등록됨": "Technical rider available",
  "기술자료 필요": "Technical rider needed",
  "조건에 맞는 아티스트가 없습니다.": "No artists match these filters.",
  "이 아티스트 부킹": "Book this artist",
  "아티스트 수정": "Edit artist",
  "연락 담당자": "Contact person",
  에이전시: "Agency",
  "소개·프레스 자료": "Press materials",
  기술자료: "Technical rider",
  "팀 내부 메모": "Internal team notes",
  "함께한 행사와 진행 중인 부킹": "Past events and current bookings",
  "아직 연결된 부킹이 없습니다.": "No bookings yet.",
  "아티스트 정보 수정": "Edit artist",
  "아티스트 저장": "Save artist",
  "아티스트 이름": "Artist name",
  "거점 도시": "Base city",
  "소개·공연 구성": "Biography and performance format",
  "소개·프레스 자료 URL": "Press materials URL",
  "기술자료 URL": "Technical rider URL",
  "아티스트 정보를 저장했습니다.": "Artist information saved.",
  문의: "Enquiry",
  "조율 중": "Negotiating",
  홀드: "Hold",
  확정: "Confirmed",
  완료: "Completed",
  취소: "Cancelled",
  "홀드 재확인": "Hold needs review",
  "부킹 수정": "Edit booking",
  "새 부킹": "New booking",
  "부킹 저장": "Save booking",
  "아티스트 선택": "Select artist",
  "부킹 담당자": "Booking owner",
  "진행 상태": "Progress",
  "다음 할 일": "Next action",
  "가능한 시간 확인, 기술자료 요청 등": "Check availability, request a rider…",
  "후속 업무 기한": "Follow-up due date",
  "출연 일정": "Performance schedule",
  "출연 시작 일시": "Performance start date and time",
  "출연 종료 일시": "Performance end date and time",
  "장소·무대": "Location / stage",
  "상대 일정 가능 여부": "Artist availability",
  미확인: "Not checked",
  "가능 확인": "Available",
  불가: "Unavailable",
  "홀드 기한": "Hold expires",
  "겹치는 일정이 있습니다": "Schedule conflicts found",
  "확정 일정과 겹치면 부킹 확정 불가":
    "Resolve confirmed schedule conflicts before confirming",
  "도착·사운드체크": "Arrival and soundcheck",
  "도착 일시": "Arrival time",
  "사운드체크 일시": "Soundcheck time",
  "이 행사에 사용할 자료": "Materials for this event",
  "기술·준비 요청사항": "Technical and preparation requirements",
  "프로필 자료로 교체": "Replace with profile materials",
  "시간·장소·자료 변경 시 아티스트 재확인":
    "Artist acknowledgement required after time, location or material changes",
  "부킹을 저장했습니다.": "Booking saved.",
  "아티스트 화면 미리보기": "Preview artist view",
  "일정 버전 {version}": "Schedule version {version}",
  출연: "Performance",
  도착: "Arrival",
  사운드체크: "Soundcheck",
  "응답 저장": "Save response",
  "일정 가능 여부": "Availability",
  "아직 확인 중": "Still checking",
  가능합니다: "Available",
  "조정이 필요합니다": "Needs adjustment",
  "위 출연 일정과 준비사항을 확인했습니다":
    "I have reviewed the schedule and preparation details",
  "아티스트 응답을 반영했습니다.": "Artist response recorded.",
  "게스트 링크 준비": "Prepare guest link",
  "비활성 링크 만들기": "Create inactive link",
  "게스트 한도": "Guest limit",
  "게스트 링크를 준비했습니다. 링크 관리에서 확인 후 활성화하세요.":
    "Guest link prepared. Review and activate it in Links.",
  "무대 미정": "Stage not set",
  "홀드 기한이 지났습니다. 상대에게 일정을 다시 확인하세요.":
    "The hold has expired. Reconfirm the date with the artist.",
  "겹치는 일정 {count}건": "{count} schedule conflicts",
  "상대 일정": "Artist availability",
  "조정 필요": "Needs adjustment",
  "기한 미정": "No due date",
  "담당자 미정": "Unassigned",

  "최신 일정 확인 대기": "Awaiting latest schedule acknowledgement",
  "행사 준비 열기": "Open event preparation",
  "연결된 게스트 링크": "Open linked guest list",
  "게스트 링크 활성": "Guest link active",
  "게스트 링크 비활성": "Guest link inactive",
  "한도 {count}명": "Limit: {count} guests",
  "부킹 확정": "Confirm booking",
  "출연 완료": "Mark performance completed",
  "부킹 취소": "Cancel booking",
  "이 일정으로 부킹을 확정할까요?": "Confirm this booking?",
  "부킹을 취소할까요?": "Cancel this booking?",
  "출연을 완료로 기록할까요?": "Mark this performance as completed?",
  "상대와 합의한 일시·무대를 확인하세요. 확정해도 외부 메시지나 게스트 링크가 자동 발송되지 않습니다.":
    "Review the agreed time and stage. Confirming does not automatically send messages or guest links.",
  "기존 게스트와 링크는 유지됩니다. 필요한 변경은 링크·명단에서 별도로 확인하세요.":
    "Existing guests and links remain. Review any necessary changes in Links and Guest list.",
  "출연 이력에 완료로 남깁니다.":
    "The performance will be recorded as completed.",
  "부킹 상태를 변경했습니다.": "Booking status updated.",
  "변경 이력": "Change history",
  "조율 중인 부킹": "Bookings in progress",
  "확인이 필요한 일정": "Schedules to review",
  "부킹 검색": "Search bookings",
  "아티스트·행사·담당자": "Artist, event or owner",
  "행사 필터": "Filter by event",
  "모든 행사": "All events",
  "부킹 상태 필터": "Filter by status",
  "진행 중": "In progress",
  "확인 필요": "Needs review",
  "전체 이력": "All history",
  "부킹 보기": "Booking view",
  목록: "List",
  보드: "Board",
  "부킹 {count}건": "{count} bookings",
  "상태별 부킹 보드": "Bookings by status",
  "등록된 부킹 없음": "No bookings",
  "조건에 맞는 부킹이 없습니다.": "No bookings match these filters.",
  "일정 겹침 확인": "Review schedule conflict",
  "상대 확인 대기": "Awaiting acknowledgement",
  "이전 주": "Previous",
  "다음 주": "Next",
  "기준 날짜": "Reference date",
  "아티스트 필터": "Filter by artist",
  "모든 아티스트": "All artists",
  "일정 보기": "Calendar view",
  주간: "Week",
  오늘: "Today",
  "미확정 일정 포함": "Include tentative bookings",
  "주간 날짜 선택": "Select a day",
  월: "Mon",
  화: "Tue",
  수: "Wed",
  목: "Thu",
  금: "Fri",
  토: "Sat",
  일: "Sun",
  "주 전체 보기": "Show full week",
  전날부터: "From prior day",
  "다음 날": "Next day",
  "선택한 기간에 등록된 출연 일정이 없습니다.":
    "No performances recorded for this period.",
  "날짜 조율이 필요한 부킹": "Bookings without dates",
  "준비할 행사": "Event to prepare",
  "확정 출연 {count}팀": "{count} confirmed acts",
  "남은 업무 {count}건": "{count} open tasks",
  "자료·확인 필요 {count}팀": "{count} acts need materials or review",
  "행사 출연표": "Running order",
  "이 행사에 연결된 부킹이 없습니다.": "No bookings linked to this event.",
  "준비 체크리스트": "Preparation checklist",
  "업무 추가": "Add task",
  "미완료만 보기": "Show open tasks only",
  "기한 지남": "Overdue",
  "남은 준비 업무가 없습니다.": "No open preparation tasks.",
  "준비 업무를 추가해보세요.": "Add a preparation task.",
  "출연 자료와 일정 확인": "Materials and schedule acknowledgements",
  "부킹 열기": "Open booking",
  "최신 일정 확인 완료": "Latest schedule acknowledged",
  "이 행사 게스트 명단": "Event guest list",
  "준비 업무 추가": "Add preparation task",
  "부킹을 먼저 연결한 뒤 준비 업무를 추가하세요.":
    "Link a booking before adding preparation tasks.",
  "업무 저장": "Save task",
  "연결할 아티스트": "Artist for this task",
  "준비할 내용": "Task",
  "사진 받기, 장비 확인 등": "Collect photos, check equipment…",
  "업무 담당자": "Task owner",
  "업무 기한": "Task due date",
  "준비 완료로 기록했습니다.": "Task marked complete.",
  "준비 업무를 다시 열었습니다.": "Task reopened.",
  "준비 업무를 추가했습니다.": "Preparation task added.",
  "출연표·준비 업무": "Running order and preparation",
  미등록: "Not provided",
  "최신 내용을 확인할 수 없어 변경을 잠시 멈췄습니다. 다시 확인해주세요.":
    "Changes are paused until the latest information can be checked.",
  "최신 내용 확인": "Check latest information",
  "인터넷에 연결한 뒤 다시 저장해주세요. 입력 내용은 유지됩니다.":
    "Reconnect to the internet and save again. Your input has been kept.",
  "최신 내용을 확인한 뒤 다시 저장해주세요. 입력 내용은 유지됩니다.":
    "Check the latest information before saving. Your input has been kept.",
  "아티스트 이름을 입력해주세요.": "Enter the artist name.",
  "자료 링크는 http 또는 https 주소를 입력해주세요.":
    "Use an HTTP or HTTPS address for materials.",
  "이메일 주소를 확인해주세요.": "Check the email address.",
  "출연 시작과 종료 일시를 모두 입력해주세요.":
    "Enter both performance start and end times.",
  "종료 일시는 시작보다 늦어야 합니다. 자정 이후에는 다음 날짜를 선택해주세요.":
    "The end must be after the start. Select the next date for times after midnight.",
  "도착 일시는 출연 시작 이전으로 입력해주세요.":
    "Arrival must be before the performance starts.",
  "사운드체크는 도착 이후, 출연 시작 이전으로 입력해주세요.":
    "Soundcheck must be after arrival and before the performance.",
  "홀드 기한을 확인해주세요.": "Check the hold expiry time.",
  "아티스트를 선택해주세요.": "Select an artist.",
  "행사를 선택해주세요.": "Select an event.",
  "출연 일시·무대·담당자를 입력한 뒤 확정해주세요.":
    "Set the performance time, stage and owner before confirming.",
  "상대에게 일정 가능 여부를 확인한 뒤 확정해주세요.":
    "Check the artist's availability before confirming.",
  "홀드 기한이 지났습니다. 일정을 재확인하고 기한을 갱신하거나 조율 상태로 변경해주세요.":
    "The hold has expired. Reconfirm availability, then extend the hold or return to negotiation.",
  "확정된 일정과 겹칩니다. 아티스트 또는 무대의 시간을 조정해주세요.":
    "This conflicts with a confirmed booking. Adjust the artist or stage schedule.",
  "부킹이 변경되었습니다. 최신 내용을 확인해주세요.":
    "This booking has changed. Review the latest information.",
  "부킹이 변경되었습니다. 닫고 최신 내용을 다시 확인해주세요.":
    "This booking has changed. Close and reopen it to review the latest information.",
  "부킹 생성": "Booking created",
  "부킹 내용 수정": "Booking updated",
  "기술자료 제출 · 운영팀 검토 필요":
    "Technical rider submitted · Team review needed",
  "출연 일정 확인": "Schedule acknowledged",
  "일정 가능 여부 응답": "Availability response",
  "게스트 링크 준비 · 비활성": "Guest link prepared · Inactive",
  "부킹 상태 변경 · 문의": "Status changed · Enquiry",
  "부킹 상태 변경 · 조율 중": "Status changed · Negotiating",
  "부킹 상태 변경 · 홀드": "Status changed · Hold",
  "부킹 상태 변경 · 확정": "Status changed · Confirmed",
  "부킹 상태 변경 · 완료": "Status changed · Completed",
  "부킹 상태 변경 · 취소": "Status changed · Cancelled",
};
