import type { Artist, Booking, PlanningState } from "./types";
import { MOCK_NOW } from "../data/types";
export const newArtist = (scopeId: string): Artist => ({
  id: crypto.randomUUID(),
  scopeId,
  name: "",
  kind: "dj",
  city: "",
  contact: "",
  email: "",
  agency: "",
  bio: "",
  pressUrl: "",
  riderUrl: "",
  notes: "",
});
export const newBooking = (
  scopeId: string,
  eventId: string,
  artist?: Artist,
): Booking => ({
  id: crypto.randomUUID(),
  scopeId,
  artistId: artist?.id ?? "",
  eventId,
  status: "inquiry",
  owner: "",
  start: "",
  end: "",
  arrival: "",
  soundcheck: "",
  stage: "",
  changeoverMinutes: 0,
  travelMinutes: 0,
  nextAction: "일정 가능 여부 문의",
  due: "",
  holdUntil: "",
  availability: "unknown",
  notes: "",
  materials: {
    pressUrl: artist?.pressUrl ?? "",
    riderUrl: artist?.riderUrl ?? "",
    requirements: "",
  },
  tasks: [],
  revision: 1,
  acknowledgedRevision: null,
  materialsReviewedRevision: null,
  cancellation: null,
  guestLinkId: null,
  history: [],
});
export function initialPlanning(): PlanningState {
  const artists: Artist[] = [
    {
      ...newArtist("faust"),
      id: "artist-sora",
      name: "SORA",
      kind: "dj",
      city: "서울",
      contact: "SORA",
      email: "sora@example.com",
      bio: "House · Techno / DJ set",
      pressUrl: "https://example.com/sora/press",
      riderUrl: "https://example.com/sora/rider",
      notes: "재출연 문의 시 이전 공연 자료 확인",
    },
    {
      ...newArtist("faust"),
      id: "artist-milo",
      name: "MILO",
      kind: "dj",
      city: "서울",
      contact: "한지우",
      email: "booking@example.com",
      agency: "NORTH Agency",
      bio: "Electronic / DJ set",
      pressUrl: "https://example.com/milo/press",
    },
    {
      ...newArtist("faust"),
      id: "artist-wave",
      name: "WAVE FORM",
      kind: "live",
      city: "부산",
      contact: "김도현",
      email: "wave@example.com",
      agency: "Independent",
      bio: "듀오 라이브 · 신시사이저와 드럼 머신",
      riderUrl: "https://example.com/wave/rider",
      notes: "담당자에게 장비 목록 별도 확인",
    },
    {
      ...newArtist("faust"),
      id: "artist-forest",
      name: "FOREST QUARTET",
      kind: "band",
      city: "서울",
      contact: "이수빈",
      email: "forest@example.com",
      bio: "4인 밴드 · 45분 공연",
    },
    {
      ...newArtist("studio"),
      id: "studio-artist",
      name: "STUDIO RESIDENT",
      contact: "스튜디오 담당자",
      email: "studio@example.com",
    },
  ];
  const booking = (
    artist: Artist,
    id: string,
    eventId: string,
    extra: Partial<Booking>,
  ): Booking => ({
    ...newBooking(artist.scopeId, eventId, artist),
    id,
    owner: "정민",
    history: [
      {
        id: `${id}-created`,
        at: MOCK_NOW,
        actor: "admin",
        message: "부킹 생성",
      },
    ],
    ...extra,
  });
  return {
    artists,
    bookings: [
      booking(artists[0], "booking-sora", "tonight", {
        status: "confirmed",
        availability: "available",
        start: "2026-09-13T01:00",
        end: "2026-09-13T02:30",
        arrival: "2026-09-12T23:30",
        soundcheck: "2026-09-13T00:30",
        stage: "Main",
        acknowledgedRevision: 1,
        nextAction: "",
        tasks: [
          {
            id: "sora-task",
            title: "부스 장비 최종 확인",
            owner: "현장팀",
            due: "2026-09-12",
            done: false,
          },
        ],
      }),
      booking(artists[1], "booking-milo", "next", {
        status: "confirmed",
        availability: "available",
        start: "2026-09-18T23:00",
        end: "2026-09-19T00:30",
        arrival: "2026-09-18T21:00",
        soundcheck: "2026-09-18T21:30",
        stage: "Main",
        nextAction: "기술자료 요청",
        due: "2026-09-14",
        tasks: [
          {
            id: "milo-task",
            title: "기술자료 받기",
            owner: "정민",
            due: "2026-09-14",
            done: false,
          },
        ],
      }),
      booking(artists[2], "booking-wave", "next", {
        status: "hold",
        availability: "unknown",
        start: "2026-09-19T00:00",
        end: "2026-09-19T01:00",
        stage: "Main",
        holdUntil: "2026-09-12T18:00",
        nextAction: "출연 시간과 홀드 연장 확인",
        due: "2026-09-12",
        tasks: [
          {
            id: "wave-task",
            title: "스테이지 플롯 확인",
            owner: "기술팀",
            due: "2026-09-16",
            done: false,
          },
        ],
      }),
      booking(artists[3], "booking-forest", "showcase", {
        status: "inquiry",
        owner: "서연",
        nextAction: "공연 구성과 가능한 시간 문의",
        due: "2026-09-15",
        stage: "Hall A",
      }),
      booking(artists[0], "booking-history", "previous", {
        status: "completed",
        availability: "available",
        start: "2026-08-30T01:00",
        end: "2026-08-30T02:30",
        stage: "Main",
        nextAction: "",
        acknowledgedRevision: 1,
      }),
    ],
  };
}
