/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false` (hash: 185aa58942c36648a341c515f768a966)
interface __BaseEnv_Env {
	SESSIONS: KVNamespace;
	DB: D1Database;
	ASSETS: Fetcher;
	AUTHON_DEPLOYMENT_MODE: "production";
	NEXT_PUBLIC_APP_URL: "https://guest.faustseoul.kr";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTHON_DEPLOYMENT_MODE" | "NEXT_PUBLIC_APP_URL">> {}
}
