// Generated by Wrangler — do not edit manually.
// Run `wrangler types` to regenerate after wrangler.toml changes.

declare global {
  interface CloudflareEnv {
    DB: D1Database;
    SESSIONS: KVNamespace;
    JWT_SECRET: string;
    NEXT_PUBLIC_APP_URL: string;
    TERMINAL_VENUE_ID?: string;
    INTERNAL_API_SECRET?: string;
  }
}
