name = "authon-worker"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat_v2"]

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 데이터베이스 바인딩
[[d1_databases]]
binding = "DB"
database_name = "authon-db"
database_id = "b849dd4e-533e-477d-9ef8-cc2e4a00df1f"
migrations_dir = "migrations"

# KV 바인딩 - 세션 저장소
[[kv_namespaces]]
binding = "SESSIONS"
id = "c29d9d86856b41458a8112fb620ae874"
preview_id = "3c3c403d6dbb4aa7b0e8920041b12622"
